name: DebugBuild
on:
 push:
  branches:
    - master
    env:
SOLUTION_FILE_PATH: project/CG2.shn
CONFIGURATION: Debug


jobs:
 build:
  runs-on: wiondows-2022

  steps:
    -name: Checkout
    uses: actions/checkout@v4
    -name: Add MSBnild to PATH
    uses: microsof/setup-msbild@v2
    with:
       msbuild-architrcture: x64
    -name: Build
    run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}
       
